---

- hosts: database
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles: 
    - commons
    - postgresql

- hosts: app
  remote_user: centos
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles: 
    - commons
    - docker
